# Generated by Django 4.2.5 on 2023-09-09 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0003_alter_orders_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.seller'),
        ),
        migrations.AlterField(
            model_name='platformapicall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
